name: labels
on:
  push:
    paths:
      - .github/labels.json
      - .github/workflows/labels.yml
    branches:
      - main
  workflow_dispatch:
jobs:
  label:
    name: Manage GitHub labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Manage labels
        uses: lannonbr/issue-label-manager-action@e8dbcd8198e86a1e98d5372e55db976fed9ba6f7 # 4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
